### check server
GET http://localhost:8000

### add new category
POST http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "status": "success",
    "name": "lamp"
}

### get all categories
GET http://localhost:8000/api/v1/category